version: "3"
services: 
  api:
    image: vishalvasoya/fast-api-development
    depends_on:
      - postgres
    ports:
      - 80:8000
    environment:
      - DATABASE_HOSTNAME = ${DATABASE_HOSTNAME}
      - DATABASE_PORT = ${DATABASE_PORT}
      - DATABASE_PASSWORD = ${DATABASE_PASSWORD}
      - DATABASE_NAME = ${DATABASE_NAME}
      - DATABASE_USERNAME = ${DATABASE_USERNAME}
      - SECRET_KEY = ${SECRET_KEY}
      - ALGORITHAM = ${ALGORITHAM}
      - ACCESS_TOKEN_EXPIRE_MINUTE = ${ACCESS_TOKEN_EXPIRE_MINUTE}
  
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: